import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{ts,tsx}",
    "../../packages/ui/src/**/*.{ts,tsx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          DEFAULT: "var(--color-primary)",
          variant: "var(--color-primary-variant)",
          container: "var(--color-primary-container)",
        },
        secondary: {
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          DEFAULT: "var(--color-secondary)",
          light: "var(--color-secondary-light)",
          variant: "var(--color-secondary-variant)",
        },
        neutral: {
          0: "var(--color-neutral-0)",
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          250: "var(--color-neutral-250)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          950: "var(--color-neutral-950)",
        },
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-container": "var(--color-surface-container)",
        surfaceVariant: "var(--color-surface-variant)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        muted: "var(--color-muted)",
        error: {
          DEFAULT: "var(--color-error)",
          container: "var(--color-error-container)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          container: "var(--color-warning-container)",
        },
        success: {
          DEFAULT: "var(--color-success)",
          container: "var(--color-success-container)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          container: "var(--color-info-container)",
        },
        border: "var(--color-border)",
        divider: "var(--color-divider)",
        outline: "var(--color-outline)",
      },
      fontFamily: {
        sans: ["Vazir", "Vazirmatn", '"Noto Sans Arabic"', "Tahoma", "sans-serif"],
      },
      fontSize: {
        h1: ["32px", { lineHeight: "48px", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "38px", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "32px", fontWeight: "500" }],
        h4: ["18px", { lineHeight: "28px", fontWeight: "500" }],
        "body-1": ["16px", { lineHeight: "28px", fontWeight: "400" }],
        "body-2": ["14px", { lineHeight: "24px", fontWeight: "400" }],
        bodySmall: ["12px", { lineHeight: "20px", fontWeight: "400" }],
        bodyMedium: ["14px", { lineHeight: "24px", fontWeight: "400" }],
        button: ["14px", { lineHeight: "22px", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "20px", fontWeight: "400" }],
        labelSmall: ["10px", { lineHeight: "16px", fontWeight: "500" }],
        labelMedium: ["12px", { lineHeight: "20px", fontWeight: "500" }],
        labelLarge: ["14px", { lineHeight: "22px", fontWeight: "500" }],
        titleSmall: ["14px", { lineHeight: "22px", fontWeight: "600" }],
        titleMedium: ["16px", { lineHeight: "26px", fontWeight: "600" }],
      },
      borderRadius: {
        small: "var(--shape-small)",
        medium: "var(--shape-medium)",
        large: "var(--shape-large)",
      },
      spacing: {
        "1u": "4px",
        "2u": "8px",
        "3u": "12px",
        "4u": "16px",
        "6u": "24px",
        "8u": "32px",
        "12u": "48px",
      },
      boxShadow: {
        "elevation-1": "0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)",
        "elevation-3": "0 1px 3px rgba(0,0,0,0.18), 0 4px 8px rgba(0,0,0,0.10)",
        "elevation-4": "0 4px 6px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.08)",
        "elevation-8": "0 8px 16px rgba(0,0,0,0.14), 0 4px 8px rgba(0,0,0,0.08)",
      },
      keyframes: {
        "slide-in-right": {
          "0%": { transform: "translateX(100%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "scroll-reveal": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(16, 46, 74, 0.3)" },
          "50%": { boxShadow: "0 0 20px 4px rgba(16, 46, 74, 0.15)" },
        },
        "skeleton-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "slide-up-fade": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "drawer-slide-in": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "scroll-reveal": "scroll-reveal 0.6s cubic-bezier(0.4, 0.0, 0.2, 1) both",
        "shimmer": "shimmer 1.8s ease-in-out infinite",
        "gradient-shift": "gradient-shift 12s ease-in-out infinite",
        "float": "float 4s ease-in-out infinite",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
        "skeleton-pulse": "skeleton-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "slide-up-fade": "slide-up-fade 0.3s cubic-bezier(0.4, 0.0, 0.2, 1)",
        "drawer-slide-in": "drawer-slide-in 0.3s cubic-bezier(0.4, 0.0, 0.2, 1)",
      },
      screens: {
        "mobile-s": "320px",
        "mobile-l": "375px",
        tablet: "600px",
        laptop: "900px",
        desktop: "1024px",
        wide: "1440px",
      },
      transitionDuration: {
        short2: "150ms",
        short3: "200ms",
        short4: "250ms",
        medium1: "300ms",
        moderate1: "400ms",
        medium2: "400ms",
        long1: "500ms",
        long2: "600ms",
      },
      transitionTimingFunction: {
        standard: "cubic-bezier(0.2, 0, 0, 1)",
        "standard-decelerate": "cubic-bezier(0, 0, 0, 1)",
        "standard-accelerate": "cubic-bezier(0.3, 0, 1, 1)",
        emphasized: "cubic-bezier(0.2, 0, 0.2, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
