// ============================================================
// LEGALIR — Document Viewer (dispatcher)
// ============================================================
// One reusable viewer for every previewable document, regardless of
// whether it was uploaded by the user or generated by LEGALIR. It
// resolves the preview descriptor and hands off to the right renderer:
//
//   pdf         → PdfViewer   (paginated, zoom, fit-to-width)
//   image       → ImageViewer (fit, zoom, reset)
//   unsupported → UnsupportedPreview
//
// It owns the loading / error / permission-denied states so the
// individual renderers stay focused on rendering.
// ============================================================

"use client";

import React from "react";
import { useDocumentPreview } from "@/hooks/useDocuments";
import { PdfViewer } from "./pdf-viewer";
import { ImageViewer } from "./image-viewer";
import { UnsupportedPreview } from "./unsupported-preview";
import { PreviewError, PreviewLoading } from "./preview-states";

interface DocumentViewerProps {
  documentId: string;
  /** Fallback metadata while the descriptor loads. */
  fileName: string;
  mime: string;
  sizeBytes: number;
}

export function DocumentViewer({
  documentId,
  fileName,
  mime,
  sizeBytes: _sizeBytes,
}: DocumentViewerProps) {
  const { data: preview, isLoading, isError, error, refetch } = useDocumentPreview(documentId);

  if (isLoading) {
    return <PreviewLoading aspectRatio="3 / 4" label="در حال آماده‌سازی نمایشگر…" />;
  }

  if (isError || !preview) {
    // A 404 here means the document is not owned by this user (or was
    // deleted) — the API never distinguishes the two, by design.
    const notFound =
      error instanceof Error && /یافت نشد|404/.test(error.message);
    return (
      <PreviewError
        title={notFound ? "سند یافت نشد" : "پیش‌نمایش فایل بارگذاری نشد."}
        message={
          notFound
            ? "این سند وجود ندارد یا به حساب شما تعلق ندارد."
            : "ممکن است فایل در دسترس نباشد یا اتصال قطع شده باشد."
        }
        onRetry={notFound ? undefined : () => refetch()}
        downloadUrl={notFound ? null : `/api/v1/documents/${documentId}/download`}
      />
    );
  }

  const resolvedName = preview.name || fileName;
  const resolvedMime = preview.mime || mime;

  if (preview.kind === "unsupported") {
    return (
      <UnsupportedPreview
        fileName={resolvedName}
        mime={resolvedMime}
        downloadUrl={preview.downloadUrl}
      />
    );
  }

  // Supported type, but the stored bytes are missing.
  if (!preview.fileUrl) {
    return (
      <PreviewError
        message="فایل این سند در دسترس نیست."
        onRetry={() => refetch()}
        downloadUrl={preview.downloadUrl}
      />
    );
  }

  if (preview.kind === "pdf") {
    return (
      <PdfViewer
        fileUrl={preview.fileUrl}
        fileName={resolvedName}
        downloadUrl={preview.downloadUrl}
      />
    );
  }

  return (
    <ImageViewer
      fileUrl={preview.fileUrl}
      fileName={resolvedName}
      downloadUrl={preview.downloadUrl}
    />
  );
}

export type { DocumentViewerProps };
